title = "Shirley Shu"
baseURL = "https://example.com/"
theme = "hugo-resume"
languageCode = "en-us"
PygmentsCodeFences = false
PygmentsCodeFencesGuessSyntax = true
PygmentsStyle = "monokai"
enableGitInfo = false

[params]
address = "Victoria, BC, Canada"
email = "ssjtoshirley@gmail.com"
favicon = "/favicon.ico"
firstName = "Shirley"
lastName = "Shu"
phone = ""
profileImage = "img/TechChat.png"
showEducation = true
showExperience = true
showOpenSource = true
showProjects = true
showPublications = true
showQr = false
showSkills = true

[params.google]

[params.google.analytics]
trackerID = "XX-123446-01"

[[params.handles]]
link = "https://www.linkedin.com/in/shirley-shu-569763158/"
name = "LinkedIn"

[[params.handles]]
link = "https://github.com/ssjShirley"
name = "GitHub"

# [[params.handles]]
# link = "https://bitbucket.org/eddiewebb/"
# name = "Bitbucket"
# 
# [[params.handles]]
# link = "https://stackoverflow.com/users/story/82880"
# name = "Stack Overflow"
# 
# [[params.handles]]
# link = "https://keybase.io/edwardawebb"
# name = "Keybase"

[outputs]
home = ["HTML", "JSON"]

[taxonomies]
tag = "tags"